apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
      containers:
      - name: linkding
        image: sissbruecker/linkding:1.40.0
        ports:
          - containerPort: 9090
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
          - mountPath: /etc/linkding/data
            name: linkding-data-pvc
      volumes:
      - name: linkding-data-pvc
        persistentVolumeClaim:
          claimName: linkding-data-pvc
